"""Initial schema

Revision ID: 8e7dbca43d46
Revises: 
Create Date: 2026-07-05 19:06:22.911440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7dbca43d46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia', sa.String(length=50), nullable=False, server_default='basquet'))
        batch_op.alter_column('equipo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar', sa.String(length=100), nullable=True))
        batch_op.alter_column('fase',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Fase de Grupos'"))

    with op.batch_alter_table('resultados_calistenia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_resultados_competencia', 'competencias_calistenia', ['competencia_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('clave',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'1234'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('clave',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1234'"))

    with op.batch_alter_table('resultados_calistenia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('competencia_id')

    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.alter_column('fase',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Fase de Grupos'"))
        batch_op.drop_column('lugar')

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.alter_column('equipo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('competencia')

    # ### end Alembic commands ###
